### ISSUE TITLE
单位名词翻译问题

### ISSUE THREAD

**Issue by MapleEve** [iamapig120/Red-Alert-2_Simplified-Chinese-Language-Pack#1]
Gattling 不应当翻译为加特林
我查阅了所有的英文原文，包括正式的一些维基
Gattling 不是 Gatling，直接用盖特会好一些
武装直升机也是正确的翻译，不应当使用 Siege = 攻城
Clone Vat 克隆中心，复制中心
GI 不管是词典原意还是引申义都应该是美国大兵而不是盟军大兵

**Comment by iamapig120** [comment]
非常感谢您的来信该邮件已成功接收至手柄的邮箱您的建议及意见会经过阅读后成为优秀的参考选项To customers:I passed the postgraduate exam! Everything will return to normal in a few days!

**Comment by MapleEve** [comment]
Lasher 鞭笞者我没什么意见，只是都是T1单位，其它阵营都是两个字

**Comment by iamapig120** [comment]
感谢，我提交给翻译参考一下，以及欢迎来 QQ群 293292761 直接和翻译人员对线

**Comment by iamapig120** [comment]
GI 的原因是，GI一般来说一般是指美国大兵没错，但GI同时也可以指一般的军队，翻译为盟军大兵是基于考虑到阵营归属问题所做的翻译。
Clone Vat，Vat 具有这个意思（尤指工业用）大桶，大盆，瓮，缸，罐，并且符合游戏内缸形外观，才选择的这个翻译
Gattling 或 Gatling，在命令与征服系列中都有使用，且外观均为加特林机枪式外观，另德语翻译直接译作 Gatling

**Comment by iamapig120** [comment]
另外，Siege Chopper 其实更接近于红色警戒 2 自创的单位，也许更应该体现红色警戒 2 中的效果？

**Comment by MapleEve** [comment]
> 另外，Siege Chopper 其实更接近于红色警戒 2 自创的单位，也许更应该体现红色警戒 2 中的效果？

空对地直升机，统称都叫武装直升机，如果没有啥特殊要区分的话我倾向于不改。

**Comment by MapleEve** [comment]
> GI 的原因是，GI一般来说一般是指美国大兵没错，但GI同时也可以指一般的军队，翻译为盟军大兵是基于考虑到阵营归属问题所做的翻译。 Clone Vat，Vat 具有这个意思（尤指工业用）大桶，大盆，瓮，缸，罐，并且符合游戏内缸形外观，才选择的这个翻译 Gattling 或 Gatling，在命令与征服系列中都有使用，且外观均为加特林机枪式外观，另德语翻译直接译作 Gatling

GI这块从二战之后都是统称美国士兵，语音口音包括英文的对口，比如 Yes Sir 之类的也是纯正美国口音。

复制中心这个纯粹看玩家接受度吧，我的建议是能不改就不改，要不然部队回收厂就要和 MO 一样叫搅拌机了。

Gattling Tank 在韩文 cameo 中也是 개틀링 탱크，但是韩文属于音译语系，加特林做为 Gatling 的音译，个人认为不应该和 Gattling 的音译混在一起。

**Comment by iamapig120** [comment]
蓋特機槍／機砲 这个实际上也只是 加特林 音译的台湾版本音译……这里本质还是当作加特林进行音译了
复制中心 确实打算把YR部队的很多单位进行重新翻译来凸显其神棍特点

**Comment by MapleEve** [comment]
> 蓋特機槍／機砲 这个实际上也只是 加特林 音译的台湾版本音译……这里本质还是当作加特林进行音译了 复制中心 确实打算把YR部队的很多单位进行重新翻译来凸显其神棍特点

正体维基上针对加特林的词条，又译名也有盖特林，加特林機槍／機砲（英語：Gatling gun），或譯格林機槍／機砲、蓋特林機槍／機砲

单位的名称一般分为俗称和别称，在已经有俗称上再改个人认为不合适，可能是弹幕最多的那种操作
